# Generated by Django 4.1.4 on 2023-01-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwiczenia1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('kraj', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('miesiac_urodzenia', models.CharField(choices=[('I', 'Styczeń'), ('II', 'Luty'), ('III', 'Marzec'), ('IV', 'Kwiecień'), ('V', 'Maj'), ('VI', 'Czerwiec'), ('VII', 'Lipiec'), ('VIII', 'Sierpień'), ('IX', 'Wrzesień'), ('X', 'Październik'), ('XI', 'Listopad'), ('XII', 'Grudzień')], default='II', max_length=4)),
                ('data_dodania', models.DateField(auto_now=True)),
                ('druzyna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cwiczenia1.druzyna', verbose_name='Drużyna')),
            ],
            options={
                'ordering': ['nazwisko'],
            },
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
